del Ocean.Core.BrowserDetective.Console.dll.config
copy App.2007.config Ocean.Core.BrowserDetective.Console.dll.config
.\Ocean.Core.BrowserDetective.Console.exe
echo 2008
del Ocean.Core.BrowserDetective.Console.dll.config
copy App.2008.config Ocean.Core.BrowserDetective.Console.dll.config
.\Ocean.Core.BrowserDetective.Console.exe
echo 2009
del Ocean.Core.BrowserDetective.Console.dll.config
copy App.2009.config Ocean.Core.BrowserDetective.Console.dll.config
.\Ocean.Core.BrowserDetective.Console.exe
echo 2010
del Ocean.Core.BrowserDetective.Console.dll.config
copy App.2010.config Ocean.Core.BrowserDetective.Console.dll.config
.\Ocean.Core.BrowserDetective.Console.exe
echo 2011
del Ocean.Core.BrowserDetective.Console.dll.config
copy App.2011.config Ocean.Core.BrowserDetective.Console.dll.config
.\Ocean.Core.BrowserDetective.Console.exe
echo 2012
del Ocean.Core.BrowserDetective.Console.dll.config
copy App.2012.config Ocean.Core.BrowserDetective.Console.dll.config
.\Ocean.Core.BrowserDetective.Console.exe
echo 2013
del Ocean.Core.BrowserDetective.Console.dll.config
copy App.2013.config Ocean.Core.BrowserDetective.Console.dll.config
.\Ocean.Core.BrowserDetective.Console.exe
echo 2014
del Ocean.Core.BrowserDetective.Console.dll.config
copy App.2014.config Ocean.Core.BrowserDetective.Console.dll.config
.\Ocean.Core.BrowserDetective.Console.exe
echo 2015
del Ocean.Core.BrowserDetective.Console.dll.config
copy App.2015.config Ocean.Core.BrowserDetective.Console.dll.config
.\Ocean.Core.BrowserDetective.Console.exe
echo 2016
del Ocean.Core.BrowserDetective.Console.dll.config
copy App.2016.config Ocean.Core.BrowserDetective.Console.dll.config
.\Ocean.Core.BrowserDetective.Console.exe
echo 2017
del Ocean.Core.BrowserDetective.Console.dll.config
copy App.2017.config Ocean.Core.BrowserDetective.Console.dll.config
.\Ocean.Core.BrowserDetective.Console.exe
echo 2018
del Ocean.Core.BrowserDetective.Console.dll.config
copy App.2018.config Ocean.Core.BrowserDetective.Console.dll.config
.\Ocean.Core.BrowserDetective.Console.exe
echo 2019
del Ocean.Core.BrowserDetective.Console.dll.config
copy App.2019.config Ocean.Core.BrowserDetective.Console.dll.config
.\Ocean.Core.BrowserDetective.Console.exe
echo 2020
del Ocean.Core.BrowserDetective.Console.dll.config
copy App.2020.config Ocean.Core.BrowserDetective.Console.dll.config
.\Ocean.Core.BrowserDetective.Console.exe
echo 2021
del Ocean.Core.BrowserDetective.Console.dll.config
copy App.2021.config Ocean.Core.BrowserDetective.Console.dll.config
.\Ocean.Core.BrowserDetective.Console.exe
echo 2022
del Ocean.Core.BrowserDetective.Console.dll.config
copy App.2022.config Ocean.Core.BrowserDetective.Console.dll.config
.\Ocean.Core.BrowserDetective.Console.exe
echo 2023
del Ocean.Core.BrowserDetective.Console.dll.config
copy App.2023.config Ocean.Core.BrowserDetective.Console.dll.config
.\Ocean.Core.BrowserDetective.Console.exe
echo 2024
del Ocean.Core.BrowserDetective.Console.dll.config
copy App.2024.config Ocean.Core.BrowserDetective.Console.dll.config
.\Ocean.Core.BrowserDetective.Console.exe